version: '3.8'
services:
  php:
    build: ./php-apache
    volumes:
      - C:\Users\dpbum\Desktop\ximplia-ecommers\ecommerce\public:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_ricambivespa
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "9906:3306"