CREATE TABLE IF NOT EXISTS `ED_OBIETTIVO_FOTOCAMERA` (
	`ID_OBIETTIVO` int unsigned NOT NULL,
	`ID_FOTOCAMERA` int unsigned NOT NULL,
	PRIMARY KEY  (`ID_OBIETTIVO`,`ID_FOTOCAMERA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ED_RECENSIONE` (
	`ID` int(11) NOT NULL auto_increment,
	`ID_ARTICOLO` int unsigned NOT NULL,
	`NOME` varchar(100) NOT NULL,
	`VOTO` varchar(100) NOT NULL,
	`DATA` varchar(100) NOT NULL,
	`URL_IMMAGINE` varchar(1000) NULL,
	`URL` varchar(1000) NOT NULL,
	`TESTO` text NOT NULL,
	`LANG` varchar(2) NOT NULL,
	PRIMARY KEY  (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `ED_AMBASSADOR` (
	`ID` int unsigned NOT NULL auto_increment,
	`ORDINE` int unsigned NOT NULL default 0,
	`ABILITATO` tinyint NOT NULL default 1,
	`DETTAGLIO` text NOT NULL,
	`URL_MAPPING` tinyint NOT NULL default 1,
	INDEX  (`ORDINE`),
	PRIMARY KEY  (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `ED_AMBASSADOR_LANG` (
	`ID_ED_AMBASSADOR` int unsigned NOT NULL,
	`LANG` varchar(2) NOT NULL,
	`NOME` varchar(250) NOT NULL,
	`DETTAGLIO_LANG` longtext NOT NULL,
	`FIND` text NULL,
	INDEX(`NOME`),
	FOREIGN KEY (ID_ED_AMBASSADOR) REFERENCES ED_AMBASSADOR(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	PRIMARY KEY  (`ID_ED_AMBASSADOR`, `LANG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `ED_EASYDIVEPOINT` (
	`ID` int unsigned NOT NULL auto_increment,
	`ORDINE` int unsigned NOT NULL default 0,
	`ABILITATO` tinyint NOT NULL default 1,
	`DETTAGLIO` text NOT NULL,
	`URL_MAPPING` tinyint NOT NULL default 1,
	INDEX  (`ORDINE`),
	PRIMARY KEY  (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `ED_EASYDIVEPOINT_LANG` (
	`ID_ED_EASYDIVEPOINT` int unsigned NOT NULL,
	`LANG` varchar(2) NOT NULL,
	`NOME` varchar(250) NOT NULL,
	`DETTAGLIO_LANG` longtext NOT NULL,
	`FIND` text NULL,
	INDEX(`NOME`),
	FOREIGN KEY (ID_ED_EASYDIVEPOINT) REFERENCES ED_EASYDIVEPOINT(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	PRIMARY KEY  (`ID_ED_EASYDIVEPOINT`, `LANG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `ED_EASYDIVEPOINT` (
	`ID` int unsigned NOT NULL auto_increment,
	`ORDINE` int unsigned NOT NULL default 0,
	`ABILITATO` tinyint NOT NULL default 1,
	`DETTAGLIO` text NOT NULL,
	`URL_MAPPING` tinyint NOT NULL default 1,
	INDEX  (`ORDINE`),
	PRIMARY KEY  (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `ED_EASYDIVEPOINT_LANG` (
	`ID_ED_EASYDIVEPOINT` int unsigned NOT NULL,
	`LANG` varchar(2) NOT NULL,
	`NOME` varchar(250) NOT NULL,
	`DETTAGLIO_LANG` longtext NOT NULL,
	`FIND` text NULL,
	INDEX(`NOME`),
	FOREIGN KEY (ID_ED_EASYDIVEPOINT) REFERENCES ED_EASYDIVEPOINT(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	PRIMARY KEY  (`ID_ED_EASYDIVEPOINT`, `LANG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


create view PER_ARTICOLO_587 as
SELECT DISTINCT
	AA.ID_ATTRIBUTO
FROM
	ARTICOLO A,
	ARTICOLO_LANG AL,
	ARTICOLO_ATTRIBUTO AA,
	ARTICOLO_ATTRIBUTO AAK
WHERE
	AAK.ID_ENTITA = A.ID AND
	AA.ID_ENTITA = A.ID AND
	AA.TIPO = 6 AND
	AAK.TIPO = 7 AND
	AAK.ID_ATTRIBUTO = 587;
    
create view PER_ARTICOLO_586 as
SELECT DISTINCT
	AA.ID_ATTRIBUTO
FROM
	ARTICOLO A,
	ARTICOLO_LANG AL,
	ARTICOLO_ATTRIBUTO AA,
	ARTICOLO_ATTRIBUTO AAK
WHERE
	AAK.ID_ENTITA = A.ID AND
	AA.ID_ENTITA = A.ID AND
	AA.TIPO = 6 AND
	AAK.TIPO = 7 AND
	AAK.ID_ATTRIBUTO = 586;